import React, { useState } from 'react';
import { DailyBriefing } from '../types/clientTypes';
import { Sparkles, Calendar, ArrowRight, Zap, Target, BookOpen, Clock, Volume2, VolumeX, Lightbulb, FlaskConical, MessageSquare, Cloud, Search } from 'lucide-react';

interface DailyBriefingViewProps {
  briefing: DailyBriefing | null;
  onOpenSignalDetail?: (signal: any) => void;
}

export const DailyBriefingView: React.FC<DailyBriefingViewProps> = ({ briefing, onOpenSignalDetail }) => {
  const [isSpeaking, setIsSpeaking] = useState(false);

  if (!briefing) {
    return (
      <div className="bg-surface rounded-xl border border-outline p-10 text-center text-on-surface-variant font-mono shadow-sm">
        <Sparkles className="w-8 h-8 text-primary mx-auto mb-3" />
        <p className="font-bold text-on-background">Autonomous Daily Briefing is being generated by Dori...</p>
      </div>
    );
  }

  const handleSpeakBriefing = () => {
    if (!('speechSynthesis' in window)) {
      alert('Speech synthesis is not supported in this browser.');
      return;
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const textToRead = `Good day! Here is your AWS Signal Daily Briefing for ${briefing.date}. ${briefing.title}. Top signal of the day: ${briefing.top_signal?.title || ''}. What changed: ${briefing.what_changed}. Why developers care: ${briefing.why_developers_care}. Community pulse: ${briefing.community_pulse}.`;
    
    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.rate = 1.0;
    utterance.pitch = 1.1;

    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div className="space-y-6 font-mono text-on-background">
      {/* Hero Briefing Banner */}
      <div className="bg-surface rounded-xl border border-outline p-6 shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-4 mb-4 pb-4 border-b border-outline">
          <div className="flex items-center gap-2 text-primary font-bold text-xs uppercase tracking-wider">
            <Calendar className="w-4 h-4" />
            <span>AWS Signal Daily Brief — {briefing.date}</span>
          </div>

          <div className="flex items-center gap-3">
            {/* Audio Briefing Button */}
            <button
              onClick={handleSpeakBriefing}
              className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-bold transition-all shadow-sm cursor-pointer ${
                isSpeaking
                  ? 'bg-amber-500 text-white'
                  : 'bg-primary hover:bg-primary-container text-white'
              }`}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="w-4 h-4" />
                  <span>Stop Voice</span>
                </>
              ) : (
                <>
                  <Volume2 className="w-4 h-4" />
                  <span>Listen to Audio Briefing</span>
                </>
              )}
            </button>

            <span className="text-xs text-on-surface-variant hidden sm:inline font-mono">Generated at 08:00 AM</span>
          </div>
        </div>

        <h1 className="text-xl sm:text-2xl font-black font-display text-on-background mb-5 uppercase tracking-tight leading-tight">
          {briefing.title}
        </h1>

        {/* Top Signal Highlight */}
        {briefing.top_signal && (
          <div className="bg-surface-low border border-outline rounded-lg p-5 text-on-background mb-5 shadow-sm">
            <div className="flex items-center justify-between gap-2 mb-2">
              <span className="bg-surface text-primary text-xs font-bold px-2.5 py-0.5 rounded border border-outline uppercase tracking-wider flex items-center gap-1">
                <Zap className="w-3.5 h-3.5 text-primary" />
                TOP SIGNAL OF THE DAY
              </span>
              <span className="text-xs font-bold text-[#fe9800]">
                Score: {briefing.top_signal.signal_score}/100
              </span>
            </div>

            <h3 className="text-base sm:text-lg font-bold text-on-background mb-1.5 leading-snug font-sans">
              {briefing.top_signal.title}
            </h3>

            <p className="text-on-surface-variant text-xs sm:text-sm mb-3.5 leading-relaxed font-sans">
              {briefing.top_signal.summary}
            </p>

            <button
              onClick={() => onOpenSignalDetail && onOpenSignalDetail(briefing.top_signal)}
              className="inline-flex items-center gap-1.5 bg-surface hover:bg-surface-container text-on-background border border-outline px-3.5 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wider transition-all cursor-pointer"
            >
              <span>Explore Top Signal</span>
              <ArrowRight className="w-3.5 h-3.5 text-primary" />
            </button>
          </div>
        )}

        {/* Grid Sections: What Changed & Why Care */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-5">
          <div className="bg-surface-low border border-outline rounded-lg p-4">
            <h3 className="font-bold text-on-background text-xs mb-2 flex items-center gap-1.5 uppercase tracking-wide">
              <Zap className="w-4 h-4 text-primary" />
              What Changed
            </h3>
            <p className="text-on-surface-variant text-xs sm:text-sm leading-relaxed font-sans">
              {briefing.what_changed}
            </p>
          </div>

          <div className="bg-surface-low border border-outline rounded-lg p-4">
            <h3 className="font-bold text-on-background text-xs mb-2 flex items-center gap-1.5 uppercase tracking-wide">
              <Target className="w-4 h-4 text-[#fe9800]" />
              Why Developers Should Care
            </h3>
            <p className="text-on-surface-variant text-xs sm:text-sm leading-relaxed font-sans">
              {briefing.why_developers_care}
            </p>
          </div>
        </div>

        {/* Community Pulse */}
        <div className="bg-surface-low border border-outline rounded-lg p-4 mb-5">
          <h3 className="font-bold text-on-background text-xs mb-2 flex items-center gap-1.5 uppercase tracking-wide">
            <MessageSquare className="w-4 h-4 text-[#fe9800]" />
            Community Pulse
          </h3>
          <p className="text-on-surface-variant text-xs sm:text-sm leading-relaxed font-sans">
            {briefing.community_pulse}
          </p>
        </div>

        {/* AWS Service Spotlight */}
        <div className="bg-surface-low border border-outline rounded-lg p-5 mb-5">
          <span className="text-[10px] font-bold text-[#fe9800] bg-surface px-2 py-0.5 rounded uppercase tracking-wider mb-2 inline-flex items-center gap-1 border border-outline">
            <Cloud className="w-3.5 h-3.5 text-[#fe9800]" />
            SERVICE SPOTLIGHT
          </span>
          <h3 className="text-base font-bold text-on-background mb-1.5 font-sans">
            {briefing.service_spotlight.service_name}
          </h3>
          <p className="text-on-surface-variant text-xs sm:text-sm mb-2.5 leading-relaxed font-sans">
            {briefing.service_spotlight.description}
          </p>
          <div className="text-xs text-on-background font-semibold bg-surface p-3 rounded-lg border border-outline flex items-start gap-2">
            <Lightbulb className="w-4 h-4 text-[#fe9800] shrink-0 mt-0.5" />
            <span>Why try it: {briefing.service_spotlight.why_try}</span>
          </div>
        </div>

        {/* Try This Today */}
        <div className="bg-surface-low border border-[#00d294]/30 rounded-lg p-5 mb-5">
          <div className="flex items-center justify-between gap-2 mb-2">
            <span className="text-[10px] font-bold text-[#00d294] bg-surface px-2 py-0.5 rounded uppercase tracking-wider border border-[#00d294]/30 flex items-center gap-1">
              <FlaskConical className="w-3.5 h-3.5 text-[#00d294]" />
              TRY THIS TODAY
            </span>
            <span className="text-xs text-on-surface-variant font-semibold flex items-center gap-1">
              <Clock className="w-3.5 h-3.5 text-[#00d294]" />
              {briefing.try_today.estimated_minutes} min practical task
            </span>
          </div>

          <h3 className="text-base font-bold text-on-background mb-1.5 font-sans">
            {briefing.try_today.title}
          </h3>

          <p className="text-on-surface-variant text-xs sm:text-sm mb-3.5 leading-relaxed font-sans">
            {briefing.try_today.description}
          </p>

          <a
            href={briefing.try_today.doc_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 bg-[#00d294] hover:bg-[#00baa7] text-zinc-950 px-3.5 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wider shadow-sm transition-all"
          >
            <span>Start Hands-On Guide</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </a>
        </div>

        {/* Watchlist */}
        <div className="pt-4 border-t border-outline">
          <h3 className="font-bold text-on-background text-xs mb-2.5 flex items-center gap-1.5 uppercase tracking-wide">
            <BookOpen className="w-4 h-4 text-on-surface-variant" />
            Agent Watchlist (Topics being monitored)
          </h3>
          <div className="flex flex-wrap gap-1.5">
            {briefing.watchlist.map((item, idx) => (
              <span key={idx} className="text-xs font-semibold px-2.5 py-1 rounded-md bg-surface-low text-on-surface-variant border border-outline flex items-center gap-1">
                <Search className="w-3 h-3 text-primary" />
                <span>{item}</span>
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
export default DailyBriefingView;
