import React, { useState } from 'react';
import { DailyBriefing } from '../types/clientTypes';
import { Sparkles, Calendar, ArrowRight, Zap, Target, BookOpen, Clock, Volume2, VolumeX } from 'lucide-react';

interface DailyBriefingViewProps {
  briefing: DailyBriefing | null;
  onOpenSignalDetail?: (signal: any) => void;
}

export const DailyBriefingView: React.FC<DailyBriefingViewProps> = ({ briefing, onOpenSignalDetail }) => {
  const [isSpeaking, setIsSpeaking] = useState(false);

  if (!briefing) {
    return (
      <div className="bg-white rounded-3xl border border-slate-200 p-8 text-center text-slate-500">
        <Sparkles className="w-8 h-8 text-blue-500 mx-auto mb-3 animate-pulse" />
        <p className="font-semibold">Autonomous Daily Briefing is being generated by Dori...</p>
      </div>
    );
  }

  const handleSpeakBriefing = () => {
    if (!('speechSynthesis' in window)) {
      alert('Speech synthesis is not supported in this browser.');
      return;
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const textToRead = `Good day! Here is your AWS Signal Daily Briefing for ${briefing.date}. ${briefing.title}. Top signal of the day: ${briefing.top_signal?.title || ''}. What changed: ${briefing.what_changed}. Why developers care: ${briefing.why_developers_care}. Community pulse: ${briefing.community_pulse}.`;
    
    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.rate = 1.0;
    utterance.pitch = 1.1;

    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div className="space-y-6">
      {/* Hero Briefing Banner */}
      <div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-4 mb-4 pb-4 border-b border-slate-100">
          <div className="flex items-center gap-2 text-blue-600 font-bold text-xs uppercase tracking-wider">
            <Calendar className="w-4 h-4" />
            <span>AWS Signal Daily Brief — {briefing.date}</span>
          </div>

          <div className="flex items-center gap-3">
            {/* Dori Voice Audio Briefing Button */}
            <button
              onClick={handleSpeakBriefing}
              className={`flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs font-bold transition-all shadow-xs ${
                isSpeaking
                  ? 'bg-amber-500 text-white animate-pulse'
                  : 'bg-blue-50 text-blue-700 hover:bg-blue-100 border border-blue-200'
              }`}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="w-4 h-4" />
                  <span>Stop Dori Voice</span>
                </>
              ) : (
                <>
                  <Volume2 className="w-4 h-4 text-blue-600" />
                  <span>🔊 Listen to Dori's Audio Briefing</span>
                </>
              )}
            </button>

            <span className="text-xs text-slate-400 hidden sm:inline">Generated at 08:00 AM</span>
          </div>
        </div>

        <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 mb-4 font-rounded">
          {briefing.title}
        </h1>

        {/* Top Signal Highlight */}
        {briefing.top_signal && (
          <div className="bg-gradient-to-r from-blue-600 to-indigo-600 rounded-2xl p-6 text-white mb-6 shadow-md shadow-blue-500/15">
            <div className="flex items-center justify-between gap-2 mb-2">
              <span className="bg-white/20 text-white text-xs font-extrabold px-3 py-1 rounded-full uppercase tracking-wider">
                ⚡ TOP SIGNAL OF THE DAY
              </span>
              <span className="text-xs font-bold text-blue-200">
                Score: {briefing.top_signal.signal_score}/100
              </span>
            </div>

            <h3 className="text-xl font-bold text-white mb-2 leading-snug">
              {briefing.top_signal.title}
            </h3>

            <p className="text-blue-100 text-sm mb-4 leading-relaxed">
              {briefing.top_signal.summary}
            </p>

            <button
              onClick={() => onOpenSignalDetail && onOpenSignalDetail(briefing.top_signal)}
              className="inline-flex items-center gap-2 bg-white text-blue-700 hover:bg-blue-50 px-4 py-2 rounded-xl text-xs font-bold transition-all"
            >
              <span>Explore Top Signal</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          </div>
        )}

        {/* Grid Sections: What Changed & Why Care */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div className="bg-slate-50 border border-slate-200 rounded-2xl p-5">
            <h3 className="font-bold text-slate-900 text-base mb-2 flex items-center gap-2">
              <Zap className="w-4 h-4 text-blue-600" />
              What Changed
            </h3>
            <p className="text-slate-600 text-sm leading-relaxed">
              {briefing.what_changed}
            </p>
          </div>

          <div className="bg-slate-50 border border-slate-200 rounded-2xl p-5">
            <h3 className="font-bold text-slate-900 text-base mb-2 flex items-center gap-2">
              <Target className="w-4 h-4 text-indigo-600" />
              Why Developers Should Care
            </h3>
            <p className="text-slate-600 text-sm leading-relaxed">
              {briefing.why_developers_care}
            </p>
          </div>
        </div>

        {/* Community Pulse */}
        <div className="bg-purple-50/60 border border-purple-100 rounded-2xl p-5 mb-6">
          <h3 className="font-bold text-purple-950 text-base mb-2 flex items-center gap-2">
            💬 Community Pulse
          </h3>
          <p className="text-purple-900 text-sm leading-relaxed">
            {briefing.community_pulse}
          </p>
        </div>

        {/* AWS Service Spotlight */}
        <div className="bg-amber-50/60 border border-amber-200 rounded-2xl p-6 mb-6">
          <span className="text-xs font-extrabold text-amber-800 bg-amber-200/60 px-2.5 py-0.5 rounded-full uppercase tracking-wider mb-2 inline-block">
            ☁ SERVICE SPOTLIGHT
          </span>
          <h3 className="text-lg font-bold text-slate-900 mb-2">
            {briefing.service_spotlight.service_name}
          </h3>
          <p className="text-slate-700 text-sm mb-3 leading-relaxed">
            {briefing.service_spotlight.description}
          </p>
          <div className="text-xs text-amber-900 font-semibold bg-amber-100/70 p-3 rounded-xl">
            💡 Why try it: {briefing.service_spotlight.why_try}
          </div>
        </div>

        {/* Try This Today */}
        <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-6 mb-6">
          <div className="flex items-center justify-between gap-2 mb-2">
            <span className="text-xs font-extrabold text-emerald-800 bg-emerald-200/60 px-2.5 py-0.5 rounded-full uppercase tracking-wider">
              🧪 TRY THIS TODAY
            </span>
            <span className="text-xs text-emerald-700 font-semibold flex items-center gap-1">
              <Clock className="w-3.5 h-3.5" />
              {briefing.try_today.estimated_minutes} min practical task
            </span>
          </div>

          <h3 className="text-lg font-bold text-emerald-950 mb-2">
            {briefing.try_today.title}
          </h3>

          <p className="text-emerald-900 text-sm mb-4 leading-relaxed">
            {briefing.try_today.description}
          </p>

          <a
            href={briefing.try_today.doc_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-xl text-xs font-bold shadow-sm transition-all"
          >
            <span>Start Hands-On Guide</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </a>
        </div>

        {/* Watchlist */}
        <div className="pt-4 border-t border-slate-100">
          <h3 className="font-bold text-slate-900 text-sm mb-3 flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-slate-500" />
            Agent Watchlist (Topics being monitored)
          </h3>
          <div className="flex flex-wrap gap-2">
            {briefing.watchlist.map((item, idx) => (
              <span key={idx} className="text-xs font-semibold px-3 py-1.5 rounded-xl bg-slate-100 text-slate-700 border border-slate-200">
                🔍 {item}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
