import React, { useState } from 'react';
import { DailyBriefing } from '../types/clientTypes';
import { Sparkles, Calendar, ArrowRight, Zap, Target, BookOpen, Clock, Volume2, VolumeX } from 'lucide-react';

interface DailyBriefingViewProps {
  briefing: DailyBriefing | null;
  onOpenSignalDetail?: (signal: any) => void;
}

export const DailyBriefingView: React.FC<DailyBriefingViewProps> = ({ briefing, onOpenSignalDetail }) => {
  const [isSpeaking, setIsSpeaking] = useState(false);

  if (!briefing) {
    return (
      <div className="bg-[#121216] rounded-3xl border border-[#27272a] p-10 text-center text-zinc-400 font-mono">
        <Sparkles className="w-8 h-8 text-[#AD5CFF] mx-auto mb-3 animate-pulse" />
        <p className="font-bold text-white">Autonomous Daily Briefing is being generated by Dori...</p>
      </div>
    );
  }

  const handleSpeakBriefing = () => {
    if (!('speechSynthesis' in window)) {
      alert('Speech synthesis is not supported in this browser.');
      return;
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const textToRead = `Good day! Here is your AWS Signal Daily Briefing for ${briefing.date}. ${briefing.title}. Top signal of the day: ${briefing.top_signal?.title || ''}. What changed: ${briefing.what_changed}. Why developers care: ${briefing.why_developers_care}. Community pulse: ${briefing.community_pulse}.`;
    
    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.rate = 1.0;
    utterance.pitch = 1.1;

    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  return (
    <div className="space-y-6 font-mono text-zinc-100">
      {/* Hero Briefing Banner */}
      <div className="bg-[#121216] rounded-3xl border border-[#27272a] p-6 sm:p-8 shadow-xl">
        <div className="flex flex-wrap items-center justify-between gap-4 mb-4 pb-4 border-b border-[#27272a]">
          <div className="flex items-center gap-2 text-[#AD5CFF] font-bold text-xs uppercase tracking-wider">
            <Calendar className="w-4 h-4" />
            <span>AWS Signal Daily Brief — {briefing.date}</span>
          </div>

          <div className="flex items-center gap-3">
            {/* Dori Voice Audio Briefing Button */}
            <button
              onClick={handleSpeakBriefing}
              className={`flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-bold transition-all shadow-sm cursor-pointer ${
                isSpeaking
                  ? 'bg-amber-500 text-white animate-pulse'
                  : 'bg-[#AD5CFF] hover:bg-[#9C47FF] text-white shadow-purple-glow'
              }`}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="w-4 h-4" />
                  <span>Stop Dori Voice</span>
                </>
              ) : (
                <>
                  <Volume2 className="w-4 h-4" />
                  <span>🔊 Listen to Dori's Audio Briefing</span>
                </>
              )}
            </button>

            <span className="text-xs text-zinc-500 hidden sm:inline font-mono">Generated at 08:00 AM</span>
          </div>
        </div>

        <h1 className="text-xl sm:text-3xl font-black font-display text-white mb-6 uppercase tracking-tight leading-tight">
          {briefing.title}
        </h1>

        {/* Top Signal Highlight */}
        {briefing.top_signal && (
          <div className="bg-[#09090b] border border-[#AD5CFF]/40 rounded-2xl p-6 text-white mb-6 shadow-purple-glow">
            <div className="flex items-center justify-between gap-2 mb-2">
              <span className="bg-[#AD5CFF]/20 text-[#d8b4fe] text-xs font-extrabold px-3 py-1 rounded-full uppercase tracking-wider border border-[#AD5CFF]/30">
                ⚡ TOP SIGNAL OF THE DAY
              </span>
              <span className="text-xs font-bold text-[#ffc080]">
                Score: {briefing.top_signal.signal_score}/100
              </span>
            </div>

            <h3 className="text-lg sm:text-xl font-bold text-white mb-2 leading-snug font-sans">
              {briefing.top_signal.title}
            </h3>

            <p className="text-zinc-300 text-xs sm:text-sm mb-4 leading-relaxed font-sans">
              {briefing.top_signal.summary}
            </p>

            <button
              onClick={() => onOpenSignalDetail && onOpenSignalDetail(briefing.top_signal)}
              className="inline-flex items-center gap-2 bg-[#18181b] hover:bg-[#27272a] text-white border border-[#27272a] px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider transition-all"
            >
              <span>Explore Top Signal</span>
              <ArrowRight className="w-3.5 h-3.5 text-[#AD5CFF]" />
            </button>
          </div>
        )}

        {/* Grid Sections: What Changed & Why Care */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          <div className="bg-[#09090b] border border-[#27272a] rounded-2xl p-5">
            <h3 className="font-bold text-white text-sm mb-2 flex items-center gap-2 uppercase tracking-wide">
              <Zap className="w-4 h-4 text-[#AD5CFF]" />
              What Changed
            </h3>
            <p className="text-zinc-400 text-xs sm:text-sm leading-relaxed font-sans">
              {briefing.what_changed}
            </p>
          </div>

          <div className="bg-[#09090b] border border-[#27272a] rounded-2xl p-5">
            <h3 className="font-bold text-white text-sm mb-2 flex items-center gap-2 uppercase tracking-wide">
              <Target className="w-4 h-4 text-[#ffc080]" />
              Why Developers Should Care
            </h3>
            <p className="text-zinc-400 text-xs sm:text-sm leading-relaxed font-sans">
              {briefing.why_developers_care}
            </p>
          </div>
        </div>

        {/* Community Pulse */}
        <div className="bg-[#09090b] border border-[#27272a] rounded-2xl p-5 mb-6">
          <h3 className="font-bold text-white text-sm mb-2 flex items-center gap-2 uppercase tracking-wide">
            💬 Community Pulse
          </h3>
          <p className="text-zinc-400 text-xs sm:text-sm leading-relaxed font-sans">
            {briefing.community_pulse}
          </p>
        </div>

        {/* AWS Service Spotlight */}
        <div className="bg-[#09090b] border border-[#ffc080]/30 rounded-2xl p-6 mb-6">
          <span className="text-[10px] font-bold text-[#ffc080] bg-[#ffc080]/15 px-2.5 py-0.5 rounded-full uppercase tracking-wider mb-2 inline-block border border-[#ffc080]/30">
            ☁ SERVICE SPOTLIGHT
          </span>
          <h3 className="text-base sm:text-lg font-bold text-white mb-2 font-sans">
            {briefing.service_spotlight.service_name}
          </h3>
          <p className="text-zinc-400 text-xs sm:text-sm mb-3 leading-relaxed font-sans">
            {briefing.service_spotlight.description}
          </p>
          <div className="text-xs text-[#ffc080] font-semibold bg-[#18181b] p-3 rounded-xl border border-[#27272a]">
            💡 Why try it: {briefing.service_spotlight.why_try}
          </div>
        </div>

        {/* Try This Today */}
        <div className="bg-[#09090b] border border-[#00d294]/30 rounded-2xl p-6 mb-6">
          <div className="flex items-center justify-between gap-2 mb-2">
            <span className="text-[10px] font-bold text-[#00d294] bg-[#00d294]/15 px-2.5 py-0.5 rounded-full uppercase tracking-wider border border-[#00d294]/30">
              🧪 TRY THIS TODAY
            </span>
            <span className="text-xs text-zinc-400 font-semibold flex items-center gap-1">
              <Clock className="w-3.5 h-3.5 text-[#00d294]" />
              {briefing.try_today.estimated_minutes} min practical task
            </span>
          </div>

          <h3 className="text-base sm:text-lg font-bold text-white mb-2 font-sans">
            {briefing.try_today.title}
          </h3>

          <p className="text-zinc-400 text-xs sm:text-sm mb-4 leading-relaxed font-sans">
            {briefing.try_today.description}
          </p>

          <a
            href={briefing.try_today.doc_url}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-[#00d294] hover:bg-[#00baa7] text-zinc-950 px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider shadow-md transition-all"
          >
            <span>Start Hands-On Guide</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </a>
        </div>

        {/* Watchlist */}
        <div className="pt-4 border-t border-[#27272a]">
          <h3 className="font-bold text-white text-xs mb-3 flex items-center gap-2 uppercase tracking-wide">
            <BookOpen className="w-4 h-4 text-zinc-500" />
            Agent Watchlist (Topics being monitored)
          </h3>
          <div className="flex flex-wrap gap-2">
            {briefing.watchlist.map((item, idx) => (
              <span key={idx} className="text-xs font-semibold px-3 py-1.5 rounded-xl bg-[#09090b] text-zinc-300 border border-[#27272a]">
                🔍 {item}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
export default DailyBriefingView;
